### ISSUE TITLE
json decoder error on lpi product

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#164] opened 2024-03-01 12:37 UTC
I'm trying to plot a new product (https://github.com/ARPA-SIMC/arkimaps/blob/master/recipes/lpi.yaml), the dispatch part seems to work fine but then I got a json decoder error.

Test data:  [lpi.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/14461111/lpi.tar.gz)

(the example is with eccodes filter, but with arkimet filter the result is the same)

```
./arkimaps process --grib -o out.tar < test_data/lpi_2024_3_1_0_0_0+0.grib 
Traceback (most recent call last):
  File "/tmp/dbranchini/tmppbw84q8b/renderers/renderer000.py", line 48, in <module>
    order0('/tmp/dbranchini/tmppbw84q8b')
  File "/tmp/dbranchini/tmppbw84q8b/renderers/renderer000.py", line 45, in order0
    macro.plot(*parts)
  File "/usr/lib/python3.11/site-packages/Magics/macro.py", line 696, in plot
    return _plot(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Magics/macro.py", line 586, in _plot
    _execute(n)
  File "/usr/lib/python3.11/site-packages/Magics/macro.py", line 564, in _execute
    o.execute()
  File "/usr/lib/python3.11/site-packages/Magics/macro.py", line 279, in execute
    self.set()
  File "/usr/lib/python3.11/site-packages/Magics/macro.py", line 252, in set
    Magics.set1r(key, numpy.array(self.args[key]))
  File "/usr/lib/python3.11/site-packages/Magics/Magics.py", line 125, in wrapped
    err = fn(*args)
          ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Magics/Magics.py", line 712, in set1r
    array_p = (ctypes.c_double * size)(*data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: must be real number, not numpy.str_
2024-03-01 13:33:03,012 WARNING render Task execution failed: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/dbranchini@ARPA.EMR.NET/git/arkimaps/arkimapslib/render.py", line 139, in render_asyncio
    orders = task.result()
             ^^^^^^^^^^^^^
  File "/home/dbranchini@ARPA.EMR.NET/git/arkimaps/arkimapslib/render.py", line 155, in run_render_script
    render_info = json.loads(stdout)
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by spanezz** [comment] 2024-03-05 14:47
I pushed cb9a6f5b5476184ff12d9a656fb2acefa6cc0ed6 which produces a slightly more helpful error message. What happens is that the render script fails, so it doesn't produce valid JSON. However the problem is that the render script fails.

Now the error message points out what render script fails, so using a dispatch+render with separate steps you can run the script manually.

Running reproduced the Magics error `TypeError: must be real number, not numpy.str_`. The script is autogenerated and so a bit fiddly to read, but [black](https://black.readthedocs.io/en/stable/index.html) does a good job with it, and reviewing it I found:

```py
                contour_level_list=[0, 2.0, "4.0.", 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0, 50.0],
```

One of the levels is a string instead of a number (possibly because the trailing dot makes yaml interpret it as a string). I'll try to see if I can work on expanding the linter to catch that

**Comment by spanezz** [comment] 2024-03-05 15:15
Reworking the linter to catch that is an "interesting" problem: flavours can add/change step parameters, so in order to check for consistency I would need to either pass the flavour name to the linter, or try linting for all flavour names.

Trying linting for all flavour names might be interesting, in that it can say things like "this step has nonsense arguments with this flavour". Should I try and do that?

**Comment by brancomat** [comment] 2024-03-05 15:44
This is a bit out of my league:
the issue was a typo that I couldn't track, there are two separate aspects:
- the error message was unclear (to me). Now it's a bit better, but this comes from Magics so there's little room for manoeuvre there.
- a linter would have helped but since this is the first issue of this kind (and with a coffee or two I might have catched that), I don't know how much time is worth investing in a refined linter

pinging @edigiacomo for an opinion on the matter

**Comment by edigiacomo** [comment] 2024-03-05 16:12
I'm not really sure: if you think that the recipe schema will be quite stable and not too expensive to maintain, you can try to implement the linter.

**Comment by spanezz** [comment] 2024-07-17 07:48
This should now be handled by the pydantic code that has been merged to main

**Closed by spanezz** 2024-07-17 07:48 UTC
Labels: bug
